all:tcp_server5-1 tcp_server5-2 tcp_server5-3 tcp_client5-1 tcp_client5-2 tcp_client5-3
tcp_server5-1:
	g++ -o tcp_server5-1 server1.cpp
tcp_server5-2:
	g++ -o tcp_server5-2 server2.cpp
tcp_server5-3:
	g++ -o tcp_server5-3 server3.cpp
tcp_client5-1:
	g++ -o tcp_client5-1 client1.cpp
tcp_client5-2:
	g++ -o tcp_client5-2 client2.cpp
tcp_client5-3:
	g++ -o tcp_client5-3 client3.cpp
clean: 
	rm tcp_*
