all:tcp_server6-1 tcp_server6-2 tcp_server6-3 tcp_server6-4 tcp_client6-1 tcp_client6-2 tcp_client6-3 tcp_client6-4 
tcp_server6-1:
	g++ -o tcp_server6-1 server1.cpp
tcp_server6-2:
	g++ -o tcp_server6-2 server2.cpp
tcp_server6-3:
	g++ -o tcp_server6-3 server3.cpp
tcp_server6-4:
	g++ -o tcp_server6-4 server4.cpp
tcp_client6-1:
	g++ -o tcp_client6-1 client1.cpp
tcp_client6-2:
	g++ -o tcp_client6-2 client2.cpp
tcp_client6-3:
	g++ -o tcp_client6-3 client3.cpp
tcp_client6-4:
	g++ -o tcp_client6-4 client4.cpp
clean:
	rm tcp_*
