all:tcp_server4-1 tcp_server4-2 tcp_client4-1-1 tcp_client4-1-2 tcp_client4-2-1 tcp_client4-2-2
tcp_server4-1:
	g++ -o tcp_server4-1 server1.cpp
tcp_server4-2:
	g++ -o tcp_server4-2 server2.cpp
tcp_client4-1-1:
	g++ -o tcp_client4-1-1 client1.cpp
tcp_client4-1-2:
	g++ -o tcp_client4-1-2 client12.cpp
tcp_client4-2-1:
	g++ -o tcp_client4-2-1 client2.cpp
tcp_client4-2-2:
	g++ -o tcp_client4-2-2 client22.cpp
clean: 
	rm tcp_*
